# Generated by Django 3.1.1 on 2020-11-29 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.companyprofile')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='subscribed_users',
            field=models.ManyToManyField(blank=True, default=None, through='users.Subscription', to='users.Users'),
        ),
    ]
