# Generated by Django 3.0.7 on 2020-11-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postjob', '0003_remove_jobform_favorites'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='favoriteJobs',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorite', to='postjob.Jobform'),
        ),
    ]
