# Generated by Django 3.0.6 on 2020-11-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0003_remove_eventlisting_image'),
        ('users', '0002_users_favoritejobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='rsvpEvents',
            field=models.ManyToManyField(blank=True, default=None, related_name='rsvp', to='events_app.EventListing'),
        ),
    ]
