# Generated by Django 3.1.1 on 2020-11-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201129_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='subscribed_users',
            field=models.ManyToManyField(through='users.Subscription', to='users.Users'),
        ),
    ]
