# Generated by Django 3.1.1 on 2020-11-29 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_rsvpevents'),
        ('users', '0003_auto_20201129_1737'),
    ]

    operations = [
    ]
