# Generated by Django 3.0.7 on 2020-11-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('postjob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobform',
            name='favorites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorite', to='users.Users'),
        ),
    ]
