# Generated by Django 3.0.7 on 2020-11-13 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postjob', '0002_jobform_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobform',
            name='favorites',
        ),
    ]
