# Generated by Django 3.0.6 on 2020-11-02 18:49

from django.db import migrations

def fill_jobtypes(apps, schema_editor):
    type_names=['Full Time',
                'Part Time',
                'Internship',
                'Contract',
                'Temporary']
    Jobtypes = apps.get_model('postjob', 'Jobtype')
    for type in type_names:
        if Jobtypes.objects.filter(name=type).first() is None:
            new_type = Jobtypes(name=type)
            new_type.save()
class Migration(migrations.Migration):

    dependencies = [
        ('postjob', '0004_auto_20201102_1331'),
    ]

    operations = [
        migrations.RunPython(fill_jobtypes)
    ]
