# Generated by Django 3.0.6 on 2020-11-02 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postjob', '0005_auto_20201102_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobform',
            name='category',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='postjob.Category'),
            preserve_default=False,
        ),
    ]
