# Generated by Django 3.0.7 on 2020-11-18 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postjob', '0006_jobform_category'),
        ('postjob', '0003_remove_jobform_favorites'),
    ]

    operations = [
    ]
