# Generated by Django 3.0.6 on 2020-10-11 18:18

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postjob', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25), null=True, size=None)),
                ('status', models.CharField(choices=[('PR', 'Pending Review'), ('AC', 'Accepted'), ('RJ', 'Rejected'), ('SB', 'Submitted')], default='SB', max_length=2)),
                ('submission_date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.CompanyProfile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postjob.Jobform')),
            ],
        ),
    ]
