# Generated by Django 3.0.6 on 2020-09-07 00:16

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postjob', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Files', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25), null=True, size=None)),
                ('Applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users')),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postjob.Jobform')),
            ],
        ),
    ]
