# Generated by Django 3.0.6 on 2020-09-14 20:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
        ('postjob', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25), null=True, size=None)),
                ('status', models.CharField(choices=[('PR', 'Pending Review'), ('AC', 'Accepted'), ('RJ', 'Rejected'), ('SB', 'Submitted')], default='SB', max_length=2)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postjob.Jobform')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apply.Application')),
            ],
        ),
    ]
