# Generated by Django 3.0.6 on 2020-09-07 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='Applicant',
            new_name='applicant',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='Files',
            new_name='files',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='Job',
            new_name='job',
        ),
    ]
