# Generated by Django 3.0.6 on 2020-10-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
