# Generated by Django 3.0.6 on 2020-09-18 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0003_auto_20201011_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PR', 'Pending Review'), ('AC', 'Accepted'), ('RJ', 'Rejected'), ('SB', 'Submitted')], default='SB', max_length=2),
        ),
        migrations.DeleteModel(
            name='ApplicationStatus',
        ),
        migrations.AddField(
            model_name='applicationnotes',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apply.Application'),
        ),
    ]
