# Generated by Django 3.0.6 on 2020-10-02 20:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('apply', '0004_auto_20200918_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.CompanyProfile'),
        ),
        migrations.AddField(
            model_name='application',
            name='submission_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
